### PR TITLE
New CI stuff

### PR DESCRIPTION
**Pull request by daniel-panhead**
Add ESLint to CI pipeline

### CODE REVIEW

**Review by IcedTea2K — APPROVED** [review]
Dope, quick question though. Is it going to run eslint on merge or is it going to raise warning/errors when me make a poo poo?

**Comment by daniel-panhead** [comment]
Raises errors on poo poo

**Comment by daniel-panhead** [comment]
The CI stuff is set to run on PR creation/update

**Comment by IcedTea2K** [comment]
Wait, does the CI stuff raise the errors? Or when you run `npm run dev`?

**Comment by daniel-panhead** [comment]
When you PR it runs the tests automatically

**Comment by daniel-panhead** [comment]
It just tests to make sure `npm run lint` and `npm run build` pass without errors

**Comment by IcedTea2K** [comment]
And if there are errors, we have to fix them ourselves? Or eslint gonna do that?

**Comment by daniel-panhead** [comment]
fix it urself dum dum

**Comment by IcedTea2K** [comment]
Thanks for guiding this grandpa through. Thanks son. Merge your sexy ass

**Comment by daniel-panhead** [comment]
thanks sexy baby

**Pull request merged**
