### PR TITLE
Implement sponsors page

### PR DESCRIPTION
**Pull request by daniel-panhead**
image

Gold and silver tier images have animation when hovered on desktop

image

image

### CODE REVIEW

**Comment by daniel-panhead** [comment]
Waiting on merging `daniel/update-notebook-layout-again` to pull main and make PR

**Comment by daniel-panhead** [comment]
Decided to just merge with main and update notebook layout branch already, just merge after merging `daniel/update-notebook-layout-again` first

**Review by IcedTea2K — CHANGES_REQUESTED** [review]
Everything looks good. I like the subtle animation for each tier. But you should probably restrict the height of the logo, so they look more aligned.
image

**Comment by daniel-panhead** [comment]
Honestly I think the best solution would be to just crop the CHBE image to fit with the rest

**Comment by IcedTea2K** [comment]
> Honestly I think the best solution would be to just crop the CHBE image to fit with the rest

Which ever is easiest for you I guess.

**Comment by daniel-panhead** [comment]
image

New bronze sponsors grid :)

**Review by IcedTea2K — APPROVED** [review]
Yayy, looking better now :D

**Pull request merged**
