### PR TITLE
Lab notebook components

### PR DESCRIPTION
**Pull request by daniel-panhead**
ezpz

### CODE REVIEW

**Comment by daniel-panhead** [comment]
Still missing: smooth animation of mobile nav dropdown, scroll dots for mobile double column, fix super evil hack for smooth expand/collapse of bubbles

**Comment by daniel-panhead** [comment]
Table is pretty bad but will fix later :D

**Comment by daniel-panhead** [comment]
ok merge pls

**Comment by daniel-panhead** [comment]
okay now merge pls

**Comment by daniel-panhead** [comment]
Ok hopefully this is the last time

**Review by IcedTea2K — CHANGES_REQUESTED** [review]
Perfecto! Everything is amazing-balls.

This should be a side-by-side picture instead. Don't forget to fix the `NOTEBOOK.md` to include div  and other tags in the if necessary.
image

There should be a bit more padding to the left of the table of contents
image


Though the drop down kinda blend into the background a bit. It's a bit hard on the eye for some reason
image

Also, the footer is moving with the references/bottom bubble. UX might be a bit annoying if they accidentally clicked collapsed
image

**Review by IcedTea2K — COMMENTED** [review]
For the footer, we don't have to worry about it yet!

**Review by IcedTea2K — APPROVED** [review]
Everything looks good now. We could add this to the backlog for now, but I think the drop down for sub-pages should be aligned with the previous drop down. For example, enzyme activity assay should be on the same line as enzymosome. 
image

**Pull request merged**
